### ISSUE TITLE
phalapi-mongo auth failed

### ISSUE THREAD

**Issue by xuepengdong** [logmecn/phalapi-mongo#1]
![image](https://user-images.githubusercontent.com/10387307/111862816-b7fd6680-8992-11eb-9c3e-5dab922927c3.png)
![image](https://user-images.githubusercontent.com/10387307/111862829-c2b7fb80-8992-11eb-85e0-f230dcc196b8.png)
![image](https://user-images.githubusercontent.com/10387307/111862846-e2e7ba80-8992-11eb-8215-ae41224d5943.png)
文件中配置都是按照：https://github.com/logmecn/phalapi-mongo 配置的，mongodbmanager是可以连接上，使用phalapi-mongo就不行，麻烦问一下是什么原因呢？

**Comment by logmecn** [comment]
按我以前的经验，是因为版本过低。在我的帮助 文档 中第6条有说明。
用mongodb官方提供的版本，参考： https://www.runoob.com/mongodb/php7-mongdb-tutorial.html 。而不要用php官方提供的。
另外，mongodb-server 的版本也不要过低。

**Comment by xuepengdong** [comment]
好的非常感谢
